[default]
_default:
    just --list

# WASM / TS

build-wasm:
   wasm-pack build --out-dir target/pkg-node --target bundler --features wasm_ffi

# General

dev-setup:
    uv sync --all-extras --cache-dir .uv_cache

prod-setup:
    uv sync --all-extras --no-dev --cache-dir .uv_cache

test:
    cargo test
    uv run pytest

format:
    cargo fmt
    uv format --preview-features format

lint:
    @echo "Linting mote-api"
    uv run ty check
    cargo clippy --all-features  -- -D warnings

build: build-wasm

# Examples

rerun-demo:
    uv run rerun-demo

# CI

format-check:
    cargo fmt --check
    uv format --check --preview-features format

ci: build lint test format-check
