[book]
authors = ["Mote Contributors"]
language = "en"
src = "src"
title = "The Mote Book"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/empriselab/mote-core/tree/main/mote-book"
edit-url-template = "https://github.com/empriselab/mote-core/tree/main/mote-book/{path}"
sidebar-header-nav = false
