[default]
_default:
    just --list

build-examples:
    cargo build --examples

run-example example:
    cargo run --example {{example}}

format:
    cargo fmt

lint:
    @echo "Linting mote-api"
    cargo clippy --all-features -- -D warnings

build: build-examples

test:
    cargo test

# CI

format-check:
    cargo fmt --check

ci: build lint format-check test
