[default]
_default:
    just --list

# Build firmware
build:
    cargo build --release

# First time setup. Burns the cyw43's firmware into flash, then deploys firmware
provision:
    probe-rs download cyw43-firmware/43439A0.bin --binary-format bin --chip RP235x --base-address 0x10100000
    probe-rs download cyw43-firmware/43439A0_clm.bin --binary-format bin  --chip RP235x --base-address 0x10140000
    cargo run --release

# Deploy firmware to Mote
deploy:
    DEFMT_LOG=info cargo run --release

# Deploy firmware to Mote and run with debug logging
debug:
    DEFMT_LOG=debug cargo run --release

# Deploy firmware to Mote and run with trace logging
trace:
    DEFMT_LOG=trace cargo run --release

# Format all files
format:
    cargo fmt

# Lint all files
lint:
    @echo "Linting mote-api"
    cargo clippy --all-features -- -D warnings

format-check:
    cargo fmt --check

uf2:
    #!/usr/bin/env bash
    set -euo pipefail
    VERSION=$(grep '^version' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
    cargo build --release --features bake-cyw43-firmware
    picotool uf2 convert target/thumbv8m.main-none-eabihf/release/mote-firmware -t elf "mote-firmware-v${VERSION//./_}.uf2" --family rp2350-arm-s

ci: build format-check lint
