name: Hardware Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    shell: bash

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      hardware: ${{ steps.filter.outputs.hardware }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            hardware:
              - 'mote-hardware/**'

  drc:
    needs: filter
    if: needs.filter.outputs.hardware == 'true'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inti-cmnb/kicad9_auto:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run DRC
        working-directory: mote-hardware
        run: kibot -b mote-hardware.kicad_pcb -e mote-hardware.kicad_sch -c drc.kibot.yaml
