name: Build Rust Packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build mote-firmware
      run: cd mote-firmware && cargo build --release --verbose && cd ..
    - name: Build mote-host-driver examples
      run: cd mote-sansio-driver && cargo build --examples --verbose && cd ..
